<?php

namespace App\Tests\Functional\Users\Infrastructure\Repository;

use App\Users\Infrastructure\Repository\UserRepository;
use Doctrine\ORM\EntityRepository;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

abstract class RegisterDB extends WebTestCase
{
    protected mixed $repository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = static::getContainer()->get($this->createRepository());
    }

    abstract protected function createRepository(): string;
}
